---
traefik:
- url: http://192.168.1.100:8080/
ignore:
- app
- heimdall
- headscale
ignore_insecure: true
overrides:
  nextcloud:
    url: https://nextcloud.org
:ignore:
- app
- heimdall
- headscale
- headscaleadmin
