version: '3.8'

services:
  daeshbord:
    build: jamez001/daeshbord
    ports:
      - "9292:9292" # Optional, remove if behind traefik or other proxy on docker network
    environment:
      - APP_HOME=/app
      - CONFIG_FILE=/app/config.yml
    volumes:
      - ./config.yml:/app/config.yml
    networks:
      - daeshbord

networks:
  daeshbord:
    driver: bridge